ARG VARIANT="16-alpine3.15"

# FROM node:${VARIANT}
FROM node:16-alpine3.15

# install git
RUN apk add --no-cache git

# COPY package.json .
# COPY package-lock.json .

# RUN npm i

# COPY . .

# ENTRYPOINT [ "nginx", "-g", "daemon off;" ]